JSON visualization | viewer: http://chris.photobooks.com/json/default.htm
-------------------------------------- Code.html --------------------------------------
function auth   (){}
function size   (){Logger.log(ScriptDb.getMyDb().query({table:"bid"/*"user",seller:true,user:"atlaslive@gmail.com"*/}).getSize());}
function showOne(){Logger.log(/*Utilities.jsonStringify*/JSON.stringify(ScriptDb.getMyDb().query({table:"note"/*"user",user:"atlaslive@gmail.com",seller:true*/,city:"test"}).next()));} // Show all records in database // Reference: https://developers.google.com/apps-script/scriptdb#saving_data
function showAll(){var db=ScriptDb.getMyDb();var results=db.query({table:/*"bid"/*/"user"/*/"note"/*,seller:true,user:"atlaslive@gmail.com"*/});while(results.hasNext()){var r=results.next();Logger.log(/*Utilities.jsonStringify*/JSON.stringify(r));}} // Show all records in database // Reference: https://developers.google.com/apps-script/scriptdb#saving_data
function del    (){var xdb=ScriptDb.getMyDb(),arr=[],r,results=db.query({xtable:"note"/*"report"/* /"bid"/*"user"*/,xcity:"test"/*xseller:true,xuser* /,bidder:"atlaslive@gmail.com"*/});while(results.hasNext()){arr.push(results.next().getId());}db.removeByIdBatch(arr,false);} // Replaced: while(results.hasNext()){r=results.next();db.remove(r);}}
function mod    (){var xdb=ScriptDb.getMyDb(),r,results=db.query({xtable:"note"/*/"bid"*/});while(results.hasNext()){r=results.next();r.item=LibraryjsUtil.toBase62(Number(r.getId().slice(1)));/*if(r.askPts==""){r.askPts=0}/* /r.remove=false;r.accepted=false;/*r.askRate=r.buyRate;r.askPts=r.buyPts;* /r.bids=[];/*r.table="note";r.datePosted=new Date().getTime();* /var i=r.bids.length;while(i--){/*r.bids[i].timestamp=r.bids[i].time;* /r.bids[i].accepted=false;/*r.bids[i].target_id=r.getId();* /r.bids[i].time=""/* /if(r.bids[i].bidder=="atlaslive@gmail.com"){r.bids.splice(i,1)}*/db.save(r);}}
// function getEmailQuota(){Logger.log("Remaining email quota: " + MailApp.getRemainingDailyQuota());}
// JSON visualization | viewer: http://chris.photobooks.com/json/default.htm
// function doPost(e){return x.y();}
function doGet(e){ // References: https://developers.google.com/apps-script/guides/html-service-communication#private_functions // https://sites.google.com/site/appsscripttutorial/miscellaneous/creating-form-elements-dynamically-using-google-apps-script-gas
 // if(e && e.parameter && e.parameter.jsoncallback){return ContentService.createTextOutput("foo({result:'<strong>Hello World'});").setMimeType(ContentService.MimeType.TEXT);}
    if(e && e.parameter && e.parameter.k){var k=e.parameter.k,m=e.parameter.m,p=e.parameter;switch(k){
            case   /* account     	   */ "uaceyes6ubt0nc4ow6ng" : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<div style=\"margin-left:50px;margin-top:50px;\"><img src=\"https://lh4.googleusercontent.com/-bz-QzShfbx4/Uddv4FBoplI/AAAAAAAAHaM/iFNaaL5RB9M/s1600/My-Documents-icon.png\"                                                                 ></div>'})").setMimeType(ContentService.MimeType.JSON      );break;
            case   /* taxdocs		   */ "qcy0zn273yllnor7daj7" : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<div style=\"margin-left:50px;margin-top:50px;\"><img src=\"https://lh4.googleusercontent.com/-bz-QzShfbx4/Uddv4FBoplI/AAAAAAAAHaM/iFNaaL5RB9M/s1600/My-Documents-icon.png\"                                                                 ></div>'})").setMimeType(ContentService.MimeType.JSON      );break;
            case   /* citizen-us	   */ "hcx6ce5fj22c0ru0uh7k" : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<div style=\"margin-left:50px;margin-top:50px;\"><img src=\"https://lh4.googleusercontent.com/-bz-QzShfbx4/Uddv4FBoplI/AAAAAAAAHaM/iFNaaL5RB9M/s1600/My-Documents-icon.png\"                                                                 ></div>'})").setMimeType(ContentService.MimeType.JSON      );break;
            case   /* citizen-nonus	   */ "1w6qu34iki6orhn31va9" : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<div style=\"margin-left:50px;margin-top:50px;\"><img src=\"https://lh4.googleusercontent.com/-bz-QzShfbx4/Uddv4FBoplI/AAAAAAAAHaM/iFNaaL5RB9M/s1600/My-Documents-icon.png\"                                                                 ></div>'})").setMimeType(ContentService.MimeType.JSON      );break;
            case   /* deals			   */ "2a6ib6wqih1po8amk9kp" : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<div style=\"margin-left:50px;margin-top:50px;\"><img src=\"https://lh4.googleusercontent.com/-bz-QzShfbx4/Uddv4FBoplI/AAAAAAAAHaM/iFNaaL5RB9M/s1600/My-Documents-icon.png\"                                                                 ></div>'})").setMimeType(ContentService.MimeType.JSON      );break;
            case   /* balances         */ "23gd3r4v88h0qs5l904w" : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<div style=\"margin-left:50px;margin-top:50px;\"><img src=\"https://lh4.googleusercontent.com/-bTaY-umWq04/UKVWnKQq5-I/AAAAAAAAD3s/dDtgQsquOD4/s1600/Under-Construction.jpg\"                                                                ></div>'})").setMimeType(ContentService.MimeType.JSON      );break;
            case   /* tax-instructions */ "2632vy7qroae9ehameno" : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<div style=\"margin-left:50px;margin-top:50px;\"><img src=\"https://lh4.googleusercontent.com/-bTaY-umWq04/UKVWnKQq5-I/AAAAAAAAD3s/dDtgQsquOD4/s1600/Under-Construction.jpg\"                                                                ></div>'})").setMimeType(ContentService.MimeType.JSON      );break;
            case   /* w9-eSign		   */ "eii2t8p9pj21o812ondu" : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<div style=\"margin-left:50px;margin-top:50px;\"><img src=\"https://lh4.googleusercontent.com/-bTaY-umWq04/UKVWnKQq5-I/AAAAAAAAD3s/dDtgQsquOD4/s1600/Under-Construction.jpg\"                                                                ></div>'})").setMimeType(ContentService.MimeType.JSON      );break;
            case   /* w8-eSign		   */ "ahbcktn71r40oq5o6vut" : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<div style=\"margin-left:50px;margin-top:50px;\"><img src=\"https://lh4.googleusercontent.com/-bTaY-umWq04/UKVWnKQq5-I/AAAAAAAAD3s/dDtgQsquOD4/s1600/Under-Construction.jpg\"                                                                ></div>'})").setMimeType(ContentService.MimeType.JSON      );break;
            case   /* training-manual  */ "tn46yr3m8dovd8pyfzl2" : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<iframe style=\"xmargin-top:-200px;width:100%;height:100%\" src=\"https://docs.google.com/document/d/1tPoD_SKBc0ofqvaORp2ldbmKzT6s5cqnPOP81Pq1zk8/preview\"                                                                         ></iframe>      '})").setMimeType(ContentService.MimeType.JSON      );break;
            case   /* w9-pdf		   */ "rcgrp03ur0omffihy6h7" : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<iframe style=\"xmargin-top:-200px;width:100%;height:100%\" src=\"http://www.irs.gov/pub/irs-pdf/fw9.pdf\"                                                                                                                          ></iframe>      '})").setMimeType(ContentService.MimeType.JSON      );break;
            case   /* w8-pdf           */ "ydl609qvq0eacb4ntbut" : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<iframe style=\"xmargin-top:-200px;width:100%;height:100%\" src=\"http://www.irs.gov/pub/irs-pdf/fw8ben.pdf\"                                                                                                                       ></iframe>      '})").setMimeType(ContentService.MimeType.JSON      );break;
            case   /* register-buyer   */ "fruif01iaqqdgmqq1glu" : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<div style=\"overflow:hidden\"><iframe scrolling=\"no\"   style=\"xmargin-top:-200px;width:100%;height:1200px;\" src=\"https://sites.google.com/site/dealdiggeronline/parties/buyer/register-buyer#sites-canvas-main-content\"      ></iframe></div>'})").setMimeType(ContentService.MimeType.JSON      );break; // References // http://www.dimpost.com/2012/12/iframe-how-to-display-specific-part-of.html // http://stackoverflow.com/questions/5676672/how-do-i-crop-the-contents-of-an-iframe-to-show-a-part-of-a-page/14004622#14004622
            case   /* private-listing  */ "bim5yiet1iw5m6ey33zr" : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<div style=\"margin-left:50px;margin-top:50px;\"><img src=\"https://lh4.googleusercontent.com/-bTaY-umWq04/UKVWnKQq5-I/AAAAAAAAD3s/dDtgQsquOD4/s1600/Under-Construction.jpg\"                                                                ></div>'})").setMimeType(ContentService.MimeType.JSON      );break; // References // http://www.dimpost.com/2012/12/iframe-how-to-display-specific-part-of.html // http://stackoverflow.com/questions/5676672/how-do-i-crop-the-contents-of-an-iframe-to-show-a-part-of-a-page/14004622#14004622
            case   /* private-auction  */ "zllhi2v8cx7qre66q3z2" : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<div style=\"margin-left:50px;margin-top:50px;\"><img src=\"https://lh4.googleusercontent.com/-bTaY-umWq04/UKVWnKQq5-I/AAAAAAAAD3s/dDtgQsquOD4/s1600/Under-Construction.jpg\"                                                                ></div>'})").setMimeType(ContentService.MimeType.JSON      );break; // References // http://www.dimpost.com/2012/12/iframe-how-to-display-specific-part-of.html // http://stackoverflow.com/questions/5676672/how-do-i-crop-the-contents-of-an-iframe-to-show-a-part-of-a-page/14004622#14004622
         // case   /* public-listing   */ "cdl2t4npt1vpu0ukq7xw" : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<div style=\"overflow:hidden\"><iframe scrolling=\"no\"   style=\"xmargin-top:-200px;width:100%;height:1200px;\" src=\"https://sites.google.com/site/dealdiggeronline/parties/buyer/public-listing#sites-canvas-main-content\"      ></iframe></div>'})").setMimeType(ContentService.MimeType.JSON      );break; // References // http://www.dimpost.com/2012/12/iframe-how-to-display-specific-part-of.html // http://stackoverflow.com/questions/5676672/how-do-i-crop-the-contents-of-an-iframe-to-show-a-part-of-a-page/14004622#14004622
         // case   /* public-auction   */ "3k6d9487bgr6tc4h6cbl" : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<div style=\"overflow:hidden\"><iframe scrolling=\"no\"   style=\"xmargin-top:-200px;width:100%;height:1200px;\" src=\"http://jsfiddle.net/Ynp5Z/6/show\"                                                                           ></iframe></div>'})").setMimeType(ContentService.MimeType.JSON      );break; // References // http://www.dimpost.com/2012/12/iframe-how-to-display-specific-part-of.html // http://stackoverflow.com/questions/5676672/how-do-i-crop-the-contents-of-an-iframe-to-show-a-part-of-a-page/14004622#14004622
         // case   /* public-auction   */ "3k6d9487bgr6tc4h6cbl" : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<div style=\"overflow:hidden\"><iframe scrolling=\"no\"   style=\"xmargin-top:-200px;width:100%;height:1200px;\" src=\"https://sites.google.com/site/dealdiggeronline/parties/buyer/public-auction#sites-canvas-main-content\"      ></iframe></div>'})").setMimeType(ContentService.MimeType.JSON      );break; // References // http://www.dimpost.com/2012/12/iframe-how-to-display-specific-part-of.html // http://stackoverflow.com/questions/5676672/how-do-i-crop-the-contents-of-an-iframe-to-show-a-part-of-a-page/14004622#14004622
            case   /* listings         */ "904dtdwo1rqyjaw5spjf" : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<div style=\"overflow:hidden\"><iframe scrolling=\"no\"   style=\"xmargin-top:-200px;width:100%;height:1200px;\" src=\"https://sites.google.com/site/dealdiggeronline/parties/buyer/listings#sites-canvas-main-content\"            ></iframe></div>'})").setMimeType(ContentService.MimeType.JSON      );break; // References // http://www.dimpost.com/2012/12/iframe-how-to-display-specific-part-of.html // http://stackoverflow.com/questions/5676672/how-do-i-crop-the-contents-of-an-iframe-to-show-a-part-of-a-page/14004622#14004622
            case   /* auctions         */ "nbzuuuhxzxkkn3ln32m4" : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<div style=\"overflow:hidden\"><iframe scrolling=\"no\"   style=\"xmargin-top:-200px;width:100%;height:1200px;\" src=\"https://sites.google.com/site/dealdiggeronline/parties/buyer/auctions#sites-canvas-main-content\"            ></iframe></div>'})").setMimeType(ContentService.MimeType.JSON      );break; // References // http://www.dimpost.com/2012/12/iframe-how-to-display-specific-part-of.html // http://stackoverflow.com/questions/5676672/how-do-i-crop-the-contents-of-an-iframe-to-show-a-part-of-a-page/14004622#14004622
            case   /* pri-auc-data     */ "i2k7yas4a0t32cxw42v6" : return ContentService.createTextOutput(e.parameter.    callback+"(" + JSON.stringify(privateAuction2   ( )) + ")"                                                                                                                                                                                                                    ).setMimeType(ContentService.MimeType.JSON      );break; // References // http://www.dimpost.com/2012/12/iframe-how-to-display-specific-part-of.html // http://stackoverflow.com/questions/5676672/how-do-i-crop-the-contents-of-an-iframe-to-show-a-part-of-a-page/14004622#14004622
            case   /* seller's view    */ "ipkqkho9pnhe6yfvl4bt" : return ContentService.createTextOutput(e.parameter.    callback+"(" + JSON.stringify(serveSellers      ( )) + ")"                                                                                                                                                                                                                    ).setMimeType(ContentService.MimeType.JSON      );break; // References // http://www.dimpost.com/2012/12/iframe-how-to-display-specific-part-of.html // http://stackoverflow.com/questions/5676672/how-do-i-crop-the-contents-of-an-iframe-to-show-a-part-of-a-page/14004622#14004622
            case   /* buyer's view     */ "bhn5yy2m1ngvdo018j2k" : return ContentService.createTextOutput(e.parameter.    callback+"(" + JSON.stringify(serveBuyers       ( )) + ")"                                                                                                                                                                                                                    ).setMimeType(ContentService.MimeType.JSON      );break; // References // http://www.dimpost.com/2012/12/iframe-how-to-display-specific-part-of.html // http://stackoverflow.com/questions/5676672/how-do-i-crop-the-contents-of-an-iframe-to-show-a-part-of-a-page/14004622#14004622
            case   /* serve calendar   */ "l1hhcu5citwws2377dtt" : return ContentService.createTextOutput(e.parameter.    callback+"(" + JSON.stringify(serveCalendar     ( )) + ")"                                                                                                                                                                                                                    ).setMimeType(ContentService.MimeType.JSON      );break; // References // http://www.dimpost.com/2012/12/iframe-how-to-display-specific-part-of.html // http://stackoverflow.com/questions/5676672/how-do-i-crop-the-contents-of-an-iframe-to-show-a-part-of-a-page/14004622#14004622
            case   /* receive buy      */ "mkqwi0w4kvmm51spgrs9" : return                                                                   /* x.y() */ receiveBuy        (p)                                                                                                                                                                                                                                                                            ;break; // References // http://www.dimpost.com/2012/12/iframe-how-to-display-specific-part-of.html // http://stackoverflow.com/questions/5676672/how-do-i-crop-the-contents-of-an-iframe-to-show-a-part-of-a-page/14004622#14004622
            case   /* seller remove    */ "346f7w5jalx8cdwsfc2d" : return                                                                   /* x.y() */ receiveSell       (p)                                                                                                                                                                                                                                                                            ;break; // References // http://www.dimpost.com/2012/12/iframe-how-to-display-specific-part-of.html // http://stackoverflow.com/questions/5676672/how-do-i-crop-the-contents-of-an-iframe-to-show-a-part-of-a-page/14004622#14004622
            case   /* seller accept    */ "8u0ghdqoe4bw7ypepi0e" : return                                                                   /* x.y() */ receiveSell       (p)                                                                                                                                                                                                                                                                            ;break;
            case   /* receive report   */ "nwt0px9x22db4i03eod1" : return                                                                   /* x.y() */ receiveReport     (p)                                                                                                                                                                                                                                                                            ;break;
            case   /* Serve script JS  */ "k7fvbixefxcc1fy4eqr5" : return ContentService.createTextOutput(                                              serveScript       (k)                                                                                                                                                                                                                           ).setMimeType(ContentService.MimeType.JAVASCRIPT);break;         
            case   /* Serve script CSS */ "rcc6brjymslc37vtpb8y" : return ContentService.createTextOutput(e.parameter.    callback+"(" +                serveScript       (k)  + ")"                                                                                                                                                                                                                    ).setMimeType(ContentService.MimeType.JSON      );break;         
         // case   /* Test  script     */ "ilrav3er4xwaoejqezt2" : return ContentService.createTextOutput(                                               testScript       ( )                                                                                                                                                                                                                           ).setMimeType(ContentService.MimeType.JAVASCRIPT);break;         
         /* case   /* reports-dash    * / "                    " : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<div style=\"overflow:hidden\"><iframe scrolling=\"no\"   style=\"xmargin-top:-200px;width:100%;height:1200px;\" src=\"https://sites.google.com/site/gosalespro/manage/dashboard#sites-canvas-main-content\"                        ></iframe></div>'})").setMimeType(ContentService.MimeType.JSON      );break; // References // http://www.dimpost.com/2012/12/iframe-how-to-display-specific-part-of.html // http://stackoverflow.com/questions/5676672/how-do-i-crop-the-contents-of-an-iframe-to-show-a-part-of-a-page/14004622#14004622
            case   /* sp-dashboard    * / "                    " : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<div style=\"overflow:hidden\"><iframe scrolling=\"no\"   style=\"xmargin-top:-200px;width:100%;height:1200px;\" src=\"https://sites.google.com/site/gosalespro/manage/dashboard#sites-canvas-main-content\"                        ></iframe></div>'})").setMimeType(ContentService.MimeType.JSON      );break; // References // http://www.dimpost.com/2012/12/iframe-how-to-display-specific-part-of.html // http://stackoverflow.com/questions/5676672/how-do-i-crop-the-contents-of-an-iframe-to-show-a-part-of-a-page/14004622#14004622
            // Pages below this line do respond to the # anchor for <iframe> but we use negative margins to enable scrolling while limiting to top edge
            case   /* bugs-features   * / "                    " : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<div style=\"overflow:hidden\"><iframe scrolling=\"auto\" style=\" margin-top:-240px;width:100%;height:1500px;\" src=\"https://sites.google.com/site/gosalespro/manage/bugs-features\"                                              ></iframe></div>'})").setMimeType(ContentService.MimeType.JSON      );break; // References // http://www.dimpost.com/2012/12/iframe-how-to-display-specific-part-of.html // http://stackoverflow.com/questions/5676672/how-do-i-crop-the-contents-of-an-iframe-to-show-a-part-of-a-page/14004622#14004622
			// Pages below this line do not respond to # anchor for <iframe> so we used negative margins which also limit scrolling above top edge
            case   /* registration-sp * / "                    " : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<div style=\"overflow:hidden\"><iframe scrolling=\"auto\" style=\" margin-top:-150px;width:100%;height:1200px;\" src=\"https://sites.google.com/site/gosalespro/team/sp/apply#sites-canvas-main-content\"                           ></iframe></div>'})").setMimeType(ContentService.MimeType.JSON      );break; // References // http://www.dimpost.com/2012/12/iframe-how-to-display-specific-part-of.html // http://stackoverflow.com/questions/5676672/how-do-i-crop-the-contents-of-an-iframe-to-show-a-part-of-a-page/14004622#14004622
            case   /* objectives      * / "                    " : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<div style=\"overflow:hidden\"><iframe scrolling=\"auto\" style=\" margin-top:-250px;width:100%;height:1200px;\" src=\"https://sites.google.com/site/gosalespro/manage/objectives#sites-canvas-main-content\"                       ></iframe></div>'})").setMimeType(ContentService.MimeType.JSON      );break; // References // http://www.dimpost.com/2012/12/iframe-how-to-display-specific-part-of.html // http://stackoverflow.com/questions/5676672/how-do-i-crop-the-contents-of-an-iframe-to-show-a-part-of-a-page/14004622#14004622
			case   /* announcements   * / "                    " : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<div style=\"overflow:hidden\"><iframe scrolling=\"auto\" style=\" margin-top:-180px;width:100%;height:1200px;\" src=\"https://sites.google.com/site/gosalespro/admin/announcements#sites-canvas-main-content\"                     ></iframe></div>'})").setMimeType(ContentService.MimeType.JSON      );break; // References // http://www.dimpost.com/2012/12/iframe-how-to-display-specific-part-of.html // http://stackoverflow.com/questions/5676672/how-do-i-crop-the-contents-of-an-iframe-to-show-a-part-of-a-page/14004622#14004622
            // Data tables below this line.
            // Insert data tables here.
      */ default                                                 :                                                                                                         ;break;}}     
    if(SitesApp.getActivePage()){var pageName = SitesApp.getActivePage().getName();switch(pageName){
            case   "sell"                  : return HtmlService.createHtmlOutputFromFile("Sell.html"            ).setSandboxMode(HtmlService.SandboxMode.NATIVE           );break;
            case   "buy"                   : return HtmlService.createHtmlOutputFromFile("Buy.html"             ).setSandboxMode(HtmlService.SandboxMode.NATIVE           );break;
            case   "sandbox"               : return HtmlService.createHtmlOutputFromFile("Sandbox.html"         ).setSandboxMode(HtmlService.SandboxMode.NATIVE           );break;
            case   "authorize"             : return authorize                           (                       )                                                          ;break;
         /* case   "wholesaler_search"     : return HtmlService.createHtmlOutputFromFile("wholesaler_search"    )                                                          ;break; // HtmlService.createHtmlOutput(UrlFetchApp.fetch("https://sites.google.com/site/itr5k9zw23yzmxuaf5nb399c0ywb98/home/gasDD_wholesaler_search.html").getContentText());}
            case   "loan-application"      : return HtmlService.createTemplateFromFile  ("loanApp"              )                                               .evaluate();break;
            case   "researcher"            : return HtmlService.createTemplateFromFile  ("researcher"           )                                               .evaluate();break; // Debug: {var t=HtmlService.createTemplateFromFile("researcher").evaluate();Logger.log(t.getCodeWithComments);return t;}
            case   "agent"                 : return agent                                                                                                                ();break;
            case   "demo"                  : return demo                                                                                                                 ();break;
            case   "inventory"             : return inventory                                                                                                            ();break;                                                                                                     
            case   "sandbox2"              : return HtmlService.createHtmlOutputFromFile("sandbox2"             ).setSandboxMode(HtmlService.SandboxMode.NATIVE           );break; // Reference: https://developers.google.com/apps-script/guides/html-service-caja#setsandboxmode
            case   "lender"                : return HtmlService.createTemplateFromFile  ("lender"               )                                               .evaluate();break;
            case   "buyer_foreclosure"     : return HtmlService.createTemplateFromFile  ("buyer_foreclosure"    )                                               .evaluate();break;
            case   "private-listing"       : return HtmlService.createTemplateFromFile  ("private-listing"      )                                               .evaluate();break;
            case   "public-listing"        : return HtmlService.createTemplateFromFile  ("public-listing"       )                                               .evaluate();break;
            case   "public-auction"        : return HtmlService.createTemplateFromFile  ("public-auction"       )                                               .evaluate();break;
         // case   "private-auction"       : return HtmlService.createTemplateFromFile  ("private-auction"      )                                               .evaluate();break; // This works. But we seek an upgrade to jqWidgets, jqxGrid
         // case   "private-auction"       : return HtmlService.createHtmlOutputFromFile("private-auction1"     )                                                          ;break; // NOT WORKING in html file; switched to iframe jsfiddle // Error message: Invalid script or HTML content: https://www.sites.google.com/site/iae2mptmwylnrbz8iesqwkq8nvousn/home/jqx-all.js?attredirects=0&d=1:29+70920 - 70939: Integer literal 3155378976000000000 doesn't fit in 51 bits https://www.sites.google.com/site/iae2mptmwylnrbz8iesqwkq8nvousn/home/jqx.base.css?attredirects=0&d=1:428+28 - 29: Expected ) not . https://www.sites.google.com/site/iae2mptmwylnrbz8iesqwkq8nvousn/home/jqx.base.css?attredirects=0&d=1:428+5 - 62: Skipping malformed content 
         // case   "private-auction"       : return privateAuction2                                                                                                      ();break; // Use jsonp to populate jqxGrid (jqWidgets data table)
            case   "register-buyer"        : return HtmlService.createHtmlOutputFromFile("register-buyer"       )                                                          ;break;
            case   "register-lender"       : return HtmlService.createHtmlOutputFromFile("register-lender"      )                                                          ;break;
            case   "register-agent"        : return HtmlService.createHtmlOutputFromFile("register-agent"       )                                                          ;break;
            case   "register-auctionAgent" : return HtmlService.createHtmlOutputFromFile("register-auctionAgent")                                                          ;break;
            case   "register-researcher"   : return HtmlService.createHtmlOutputFromFile("register-researcher"  )                                                          ;break;
            case   "register-attorney"     : return HtmlService.createHtmlOutputFromFile("register-attorney"    )                                                          ;break;
      */ default                           :                                                                                                                                break;}}}
function authorize(){return HtmlService.createHtmlOutput("<div align='center' style='color:#808080;font-family:verdana;color:orange;font-weight:bold;margin-top:15px;'>Authorization successful!<div style='color:#808080;font-size:smaller;font-weight:normal;'>You may now access all features</div><img src='https://lh5.googleusercontent.com/-a81AytXYq0Q/Umtn0FrFdhI/AAAAAAAAIyE/xCYArSNCR1k/s144/orange-check-mark.png' height='100'></div>")}
function processForm_receiveFundDocs(ob){var i,user=Session.getActiveUser().getEmail(),t=new Date().getTime(),db=ScriptDb.getMyDb(),q={table:"user",seller:true,user:user},r=db.query(q).next();
    if(!r){r=q;r.record=[];r.emailList={current:[],archive:[]};}r.record.unshift(ob);r.record[0].date=t;r.emailList.current.unshift((t+","+ob.emailListString).split(/[\s,]+/)); // function test(){Logger.log("foo bar, zap-foo, baz bat".split(/[\s,]+/))} // Search term: split string by commar or space // Reference: http://stackoverflow.com/questions/1835032/regexp-split-string-by-commas-and-spaces-but-ignore-hyphenated-words
    i=r.emailList.current[0].length;while(i---1){if(r.emailList.archive.indexOf(r.emailList.current[i])==-1){r.emailList.archive.push(r.emailList.current[0][i])}}Logger.log(JSON.stringify(r));db.save(r)}
function processForm_registerSeller(ob){var i,user=Session.getActiveUser().getEmail(),t=new Date().getTime(),db=ScriptDb.getMyDb(),q={table:"user",seller:true,user:user},r=db.query(q).next();
    if(!r){r=q;r.record=[];r.emailList={current:[],archive:[]};}r.record.unshift(ob);r.record[0].timestamp=t;r.emailList.current.unshift((t+","+ob.emailListString).split(/[\s,]+/)); // function test(){Logger.log("foo bar, zap-foo, baz bat".split(/[\s,]+/))} // Search term: split string by commar or space // Reference: http://stackoverflow.com/questions/1835032/regexp-split-string-by-commas-and-spaces-but-ignore-hyphenated-words
    i=r.emailList.current[0].length;while(i---1){if(r.emailList.archive.indexOf(r.emailList.current[i])==-1){r.emailList.archive.push(r.emailList.current[0][i])}}Logger.log(JSON.stringify(r));db.save(r)}
function processForm_addNote(ob){var user=Session.getActiveUser().getEmail(),t=new Date().getTime(),db=ScriptDb.getMyDb(),u=db.query({table:"user",user:user,seller:true}).next(),i,dist=u.emailList.current[0].slice(1),site=SitesApp.getSite("onlinenoteexchange");if(!u.record[0].agreed){Logger.log(user+" did not agree to groundrules.");return}ob.table="note";ob.timestamp_posted=t;ob.seller=user;ob.remove=false;ob.accepted=false;ob.filePic=processPic(ob.filePic);ob.fileDoc=processDoc(ob.fileDoc);if(ob.askPts==""){ob.askPts=0};var id=db.save(ob).getId(),r=db.load(id);r.item=LibraryjsUtil.toBase62(Number(id.slice(1)));db.save(r);
    chromeLogoBlob=UrlFetchApp.fetch("https://lh5.googleusercontent.com/-zCLeer1r3ro/Udnn8thtnmI/AAAAAAAAHys/lWkaQnXPv_Q/s144/Google_Chrome_icon_2011.jpg").getBlob().setName("chromeLogoBlob");
    i=dist.length;while(i--){try{site.addViewer(dist[i])}catch(e){Logger.log(dist[i]+": "+e.message)}MailApp.sendEmail({to:dist[i],subject:"New loan: "+r.askRate+"%, "+r.askPts+" points",htmlBody:("<a href='https://sites.google.com/site/onlinenoteexchange/buy'>Click here</a> (item: "+r.item+") <a href='https://www.google.com/intl/en/chrome/browser/'><img src='cid:chromeLogo' height='15' style='text-decoration:none;border:0;outline:none'></a> <a href='https://www.google.com/intl/en/chrome/browser/'>Chrome required</a>.<br><br>Rate: "+r.askRate+"% +"+r.askPts+" points<br><br>Collateral:<br>"+r.sa+", "+r.city+", "+r.state+" "+r.zip+"<br>"+r.use+", "+r.beds+" beds, "+r.baths+" baths, "+r.sqft+" sqft, "+"<br><br>Loan Type: "+r.purpose+"<br>Loan Amount: $"+r.amount+"<br>Appraised Value: $"+r.appraisal+"<br>LTV: "+r.ltv+"%<br>Term: "+r.term+" months<br><br>Highlights: "+r.notes),name:"atlaslive@gmail.com",inlineImages:{chromeLogo:chromeLogoBlob/*,youtubeLogo:youtubeLogoBlob*/}});}/*Logger.log(JSON.stringify(ob));*/return}
function sendUserToClient(){var user=Session.getActiveUser().getEmail(),u=ScriptDb.getMyDb().query({table:"user",seller:true,user:user}).next();/*Logger.log(JSON.stringify(r));*/return u;}
function processDoc(blob){try{var id=DocsList.createFile(blob/*.getAs("application/pdf")*/).getId();}catch(e){Logger.log(e.message);return "";}DriveApp.getFileById(id).setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW);return DocsList.getFileById(id).getUrl();} // Reference: https://developers.google.com/apps-script/reference/base/composite-blob#getAs(String) // Reference: https://code.google.com/p/google-apps-script-issues/issues/detail?id=1660 see #37, Oct 13, 2012 // Use DocsList instead of DriveApp which will not allow document to be viewed properly
function processPic(blob){if(!blob.length){return ""}return "https://drive.google.com/uc?export=view&id="+DriveApp.createFile(blob/*.getAs("image/jpeg")*/).setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW).getId()} // Image // Reference: http://stackoverflow.com/questions/10311092/displaying-files-e-g-images-stored-in-google-drive-on-a-website // http://stackoverflow.com/questions/14717426/referencing-project-files-with-html-service > http://googleappsdeveloper.blogspot.in/2012/11/announcing-google-drive-site-publishing.html
function receiveBuy(p){/*if((p.bidPts=="")||(p.bidRate=="")){return} — Needs initial "" for first bid */Logger.log(JSON.stringify(p));var db=ScriptDb.getMyDb(),user=Session.getUser().getEmail(),t=new Date().getTime();p.db_id=LibraryjsUtil.rc4Decrypt("DktaE",p.db_id);var r=db.load(p.db_id);if(r.accepted||(r.remove||((r.askRate&&(p.bidRate<r.askRate))&&(r.askPts&&(p.bidPts<r.askPts))))){return} // Bid rate OR pts CAN exceed ask to sweeten offer — but not BOTH
    if(r.bids==null){r.bids=[]}var accepted=((p.bidRate==r.askRate)&&(p.bidPts==r.askPts));r.bids.push({bidder:user,rate:p.bidRate,points:p.bidPts,target_id:/*LibraryjsUtil.rc4Decrypt("vDMm0",r.getId())/*==*/p.db_id,timestamp:t,accepted:accepted});db.saveBatch([r,{table:"bid",target_id:/*LibraryjsUtil.rc4Decrypt("vDMm0",*/p.db_id/*==r.getId()-->Causes breakage*//*)*/,rate:p.bidRate,points:p.bidPts,bidder:user,timestamp:t,accepted:accepted}],false);if(accepted){/*Send email*/}return;}
function receiveSell(p){Logger.log(JSON.stringify(p));var db=ScriptDb.getMyDb(),user=Session.getUser().getEmail(),i,r,rb,t=new Date().getTime();switch(p.k){
    case "346f7w5jalx8cdwsfc2d"/*Remove*/:p.db_id=LibraryjsUtil.rc4Decrypt("DktaE",p.  db_id           );r=db.load(p.db_id);r.remove  =p.remove  ;r.timestamp_remove  =t;break;
    case "8u0ghdqoe4bw7ypepi0e"/*Accept*/:p.db_id=LibraryjsUtil.rc4Decrypt("vDMm0",p./*db_id*/target_id);r=db.load(p.db_id);r.accepted=p.accepted;r.timestamp_accepted=t;
        i=r.bids.length;while(i--){if(r.bids[i].bidder==LibraryjsUtil.rc4Decrypt("WnJ9n",p.bidder)&&r.bids[i].rate==p.rate&&r.bids[i].points==p.points){r.bids[i].accepted=true;break;}}
        rb=db.query({target_id:p.db_id}).next();rb.accepted=true;rb.accepted_timestamp=t;break;
    default:break;}db.save(r);return;}
function receiveReport(p){Logger.log(JSON.stringify(p));var r,db=ScriptDb.getMyDb(),user=Session.getUser().getEmail(),t=new Date().getTime();p.db_id=LibraryjsUtil.rc4Decrypt("DktaE",p.db_id);r=db.load(p.db_id);r.roi.unshift({timestamp:t,amt:p.roi});db.save(r);return;}
// --------------------------- Serve Outside GAS ---------------------------
function serveSellers(){var ob=[],arr=[],i,j,k,r,t=[],zil=[],user=Session.getUser().getEmail(),out={"totalResultsCount":0,"records":[]},db=ScriptDb.getMyDb(),q={table:"note",remove:false};if(user!="atlaslive@gmail.com"){q.seller=user}var results=db.query(q);while(results.hasNext()){r=results.next();i=out.totalResultsCount++;
    try{out.records[i]={db_id:LibraryjsUtil.rc4Encrypt("DktaE",r.getId())}}catch(e){Logger.log(e.message)}try{var currentBids=LibraryjsUtil.getCurrentBids(r.bids)||[],m=0;}catch(e){Logger.log(e.message)}try{m=currentBids.length}catch(e){Logger.log(e.message)}while(m--){currentBids[m].bidder=LibraryjsUtil.rc4Encrypt("WnJ9n",currentBids[m].bidder);currentBids[m].target_id=LibraryjsUtil.rc4Encrypt("vDMm0",currentBids[m].target_id);}var currentBidsLength=(currentBids)?currentBids.length:0;
	ob[i] = {
		"nolink"                         : {
                "item"                   : function(){try{return                 r.item                                                  }catch(e){Logger.log(e.message);return "";}}() //
            ,   "askRate"                : function(){try{return                 r.askRate                                               }catch(e){Logger.log(e.message);return "";}}() //
            ,   "askPts"                 : function(){try{return                 r.askPts                                                }catch(e){Logger.log(e.message);return "";}}() //
            ,   "borRate"                : function(){try{return                 r.borRate                                               }catch(e){Logger.log(e.message);return "";}}() //
            ,   "borPts"                 : function(){try{return                 r.borPts                                                }catch(e){Logger.log(e.message);return "";}}() //
            ,   "amount"                 : function(){try{return                 r.amount                                                }catch(e){Logger.log(e.message);return "";}}() //
            ,   "ltv"                    : function(){try{return                 r.ltv                                                   }catch(e){Logger.log(e.message);return "";}}() //
            ,   "term"                   : function(){try{return                 r.term                                                  }catch(e){Logger.log(e.message);return "";}}() //
            ,   "purpose"                : function(){try{return                 r.purpose                                               }catch(e){Logger.log(e.message);return "";}}() //
            ,   "exit"                   : function(){try{return                 r.exit                                                  }catch(e){Logger.log(e.message);return "";}}() //
            ,   "notes"                  : function(){try{return                 r.notes                                                 }catch(e){Logger.log(e.message);return "";}}() //
            ,   "sellCarry"              : function(){try{return                 r.sellCarry                                             }catch(e){Logger.log(e.message);return "";}}() //
            ,   "sa"                     : function(){try{return                 r.sa                                                    }catch(e){Logger.log(e.message);return "";}}() //
            ,   "city"                   : function(){try{return                 r.city                                                  }catch(e){Logger.log(e.message);return "";}}() //
            ,   "state"                  : function(){try{return                 r.state                                                 }catch(e){Logger.log(e.message);return "";}}() //
            ,   "zip"                    : function(){try{return                 r.zip                                                   }catch(e){Logger.log(e.message);return "";}}() //
            ,   "use"                    : function(){try{return                 r.use                                                   }catch(e){Logger.log(e.message);return "";}}() //
            ,   "beds"                   : function(){try{return                 r.beds                                                  }catch(e){Logger.log(e.message);return "";}}() //
            ,   "baths"                  : function(){try{return                 r.baths                                                 }catch(e){Logger.log(e.message);return "";}}() //
            ,   "sqft"                   : function(){try{return                 r.sqft                                                  }catch(e){Logger.log(e.message);return "";}}() //
            ,   "arv"                    : function(){try{return                 r.arv                                                   }catch(e){Logger.log(e.message);return "";}}() //
            ,   "appraisal"              : function(){try{return                 r.appraisal                                             }catch(e){Logger.log(e.message);return "";}}() //
            ,   "purPrice"               : function(){try{return                 r.purPrice                                              }catch(e){Logger.log(e.message);return "";}}() //
            ,   "payGood"                : function(){try{return                 r.payGood                                               }catch(e){Logger.log(e.message);return "";}}() //
            ,   "payBad"                 : function(){try{return                 r.payBad                                                }catch(e){Logger.log(e.message);return "";}}() //
            ,   "schedRE"                : function(){try{return                 r.schedRE                                               }catch(e){Logger.log(e.message);return "";}}() //
            ,   "filePic"                : function(){try{return                 r.filePic                                               }catch(e){Logger.log(e.message);return "";}}() //
            ,   "fileDoc"                : function(){try{return                 r.fileDoc                                               }catch(e){Logger.log(e.message);return "";}}() //
            ,   "bids"                   :                                        currentBids
            ,   "bidCount"               :                                        currentBidsLength
            ,   "accepted"               : function(){try{return                 r.accepted                                              }catch(e){Logger.log(e.message);return "";}}() //
			,   "remove"                 : function(){try{return                 r.remove                                                }catch(e){Logger.log(e.message);return "";}}() //					   
                                           }
     /* ,   "link"                       : {
				"link_googleMap"         : function(){try{return  /*OK* /        r.link.gmap                                             }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_yahoo"             : function(){try{return  /*OK* /        r.link.yahoo	   				                         }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_zillow"            : function(){try{return  /*OK* /        r.link.zillow                                           }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_zillowdetails"     : function(){try{return  /*OK* /        zil[i].links.homedetails.Text                           }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_zipRealty"         : function(){try{return                 ""                                                      }catch(e){Logger.log(e.message);return "";}}() //            
            ,	"link_eppraisal"         : function(){try{return  /*L1* /        r.avm.dataset.eppraisal.link                            }catch(e){Logger.log(e.message);return "";}}() // Errors: L1 local; L2 site suspected; L3 site confirmed; OK works; ok works but must copy/paste address
			,	"link_realtor"           : function(){try{return  /*OK* /        r.avm.dataset.realtor.link                              }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_realEstate"        : function(){try{return  /*OK* /        r.avm.dataset.realEstate.link                           }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_homeGain"          : function(){try{return  /*L3* /        r.avm.dataset.homeGain.link                             }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_trulia"            : function(){try{return  /*OK* /        r.avm.dataset.trulia.link                               }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_propertyShark"     : function(){try{return  /*ok* /        r.link.propertyShark                                    }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_neighborhoodScout" : function(){try{return  /*ok* /        r.link.neighborhoodScout                                }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_zipSkinny"         : function(){try{return  /*ok* /        r.link.zipSkinny                                        }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_chase"             : function(){try{return  /*ok* /        r.link.chase                                            }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_boa"               : function(){try{return  /*ok* /        r.link.boa                                              }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_homesCom"          : function(){try{return  /*ok* /        r.link.homesCom                                         }catch(e){Logger.log(e.message);return "";}}() //
										   } */
	} // db_id MyBid // arv rep cof com city state zip sa useCode beds baths sf sf_round lot lot_round yearBuilt taxVal taxVal_round lastSoldPrice lastSoldPrice_round lastSoldYear taxAmt taxAmt_round ask ask_round autoEst autoEst_round sdPct popCount rent rent_round ratio grm ia ia_round psf avmStatSet // link_googleMap link_yahoo link_zillow link_zillowdetails link_eppraisal link_realtor link_realEstate link_homeGain link_trulia link_propertyShark link_neighborhoodScout link_zipSkinny link_chase link_boa link_homesCom
	var keys=Object.keys(ob[i].nolink),z=keys.length;while(z--){out.records[i][keys[z]]=              ob[i].nolink[keys[z]]                                   }
     // keys=Object.keys(ob[i].  link),z=keys.length;while(z--){out.records[i][keys[z]]='<a href="' + ob[i].  link[keys[z]] + '" target="_blank">&#10151;</a>'}Logger.log(JSON.stringify(out.records[i]));
	}return out;}
function serveBuyers(){var ob=[],arr=[],i,j,k,r,t=[],zil=[],bidRate="",bidPts="",bidTime=0,user=Session.getUser().getEmail(),out={"totalResultsCount":0,"records":[]},db=ScriptDb.getMyDb(),results=db.query({table:"note",remove:false,accepted:false});while(results.hasNext()){r=results.next();i=out.totalResultsCount++;bidRate="";bidPts="";bidTime=0;
	try{out.records[i]={db_id:LibraryjsUtil.rc4Encrypt("DktaE",r.getId())};}catch(e){Logger.log(e.message)};try{j=r.bids.length;while(j--){if(r.bids[j].bidder==user&&(r.bids[j].timestamp>bidTime)){bidRate=r.bids[j].rate;bidPts=r.bids[j].points;bidTime=r.bids[j].timestamp;break;}}}catch(e){Logger.log(e.message);} // try{if(r.bids){arr[i]=r.bids;j=arr[i].length;while(j--){t[j]=0;if(arr[i][j].bidder==user&&(arr[i][j].time>t[j])/*&&(!arr[i][j].confirmed)*/){t[j]=arr[i][j].time;out.records[i].MyBid=arr[i][j].amount}}             }}catch(e){Logger.log(e.message)}; // "MyBid"
	ob[i] = {
		"nolink"                         : {
                "item"                   : function(){try{return                 r.item                                                  }catch(e){Logger.log(e.message);return "";}}() //
            ,   "askRate"                : function(){try{return                 r.askRate                                               }catch(e){Logger.log(e.message);return "";}}() //
            ,   "askPts"                 : function(){try{return                 r.askPts                                                }catch(e){Logger.log(e.message);return "";}}() //
            ,   "borRate"                : function(){try{return                 r.borRate                                               }catch(e){Logger.log(e.message);return "";}}() //
            ,   "borPts"                 : function(){try{return                 r.borPts                                                }catch(e){Logger.log(e.message);return "";}}() //
            ,   "amount"                 : function(){try{return                 r.amount                                                }catch(e){Logger.log(e.message);return "";}}() //
            ,   "ltv"                    : function(){try{return                 r.ltv                                                   }catch(e){Logger.log(e.message);return "";}}() //
            ,   "term"                   : function(){try{return                 r.term                                                  }catch(e){Logger.log(e.message);return "";}}() //
            ,   "purpose"                : function(){try{return                 r.purpose                                               }catch(e){Logger.log(e.message);return "";}}() //
            ,   "exit"                   : function(){try{return                 r.exit                                                  }catch(e){Logger.log(e.message);return "";}}() //
            ,   "notes"                  : function(){try{return                 r.notes                                                 }catch(e){Logger.log(e.message);return "";}}() //
            ,   "sellCarry"              : function(){try{return                 r.sellCarry                                             }catch(e){Logger.log(e.message);return "";}}() //
            ,   "sa"                     : function(){try{return                 r.sa                                                    }catch(e){Logger.log(e.message);return "";}}() //
            ,   "city"                   : function(){try{return                 r.city                                                  }catch(e){Logger.log(e.message);return "";}}() //
            ,   "state"                  : function(){try{return                 r.state                                                 }catch(e){Logger.log(e.message);return "";}}() //
            ,   "zip"                    : function(){try{return                 r.zip                                                   }catch(e){Logger.log(e.message);return "";}}() //
            ,   "use"                    : function(){try{return                 r.use                                                   }catch(e){Logger.log(e.message);return "";}}() //
            ,   "beds"                   : function(){try{return                 r.beds                                                  }catch(e){Logger.log(e.message);return "";}}() //
            ,   "baths"                  : function(){try{return                 r.baths                                                 }catch(e){Logger.log(e.message);return "";}}() //
            ,   "sqft"                   : function(){try{return                 r.sqft                                                  }catch(e){Logger.log(e.message);return "";}}() //
            ,   "arv"                    : function(){try{return                 r.arv                                                   }catch(e){Logger.log(e.message);return "";}}() //
            ,   "appraisal"              : function(){try{return                 r.appraisal                                             }catch(e){Logger.log(e.message);return "";}}() //
            ,   "purPrice"               : function(){try{return                 r.purPrice                                              }catch(e){Logger.log(e.message);return "";}}() //
            ,   "payGood"                : function(){try{return                 r.payGood                                               }catch(e){Logger.log(e.message);return "";}}() //
            ,   "payBad"                 : function(){try{return                 r.payBad                                                }catch(e){Logger.log(e.message);return "";}}() //
            ,   "schedRE"                : function(){try{return                 r.schedRE                                               }catch(e){Logger.log(e.message);return "";}}() //
            ,   "filePic"                : function(){try{return                 r.filePic                                               }catch(e){Logger.log(e.message);return "";}}() //
            ,   "fileDoc"                : function(){try{return                 r.fileDoc                                               }catch(e){Logger.log(e.message);return "";}}() //
            ,   "bidRate"                :                                         bidRate
            ,   "bidPts"                 :                                         bidPts
            ,   "bidTime"                :                                         bidTime
										   }
     /* ,   "link"                       : {
				"link_googleMap"         : function(){try{return  /*OK* /        r.link.gmap                                             }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_yahoo"             : function(){try{return  /*OK* /        r.link.yahoo	   				                         }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_zillow"            : function(){try{return  /*OK* /        r.link.zillow                                           }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_zillowdetails"     : function(){try{return  /*OK* /        zil[i].links.homedetails.Text                           }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_zipRealty"         : function(){try{return                 ""                                                      }catch(e){Logger.log(e.message);return "";}}() //            
            ,	"link_eppraisal"         : function(){try{return  /*L1* /        r.avm.dataset.eppraisal.link                            }catch(e){Logger.log(e.message);return "";}}() // Errors: L1 local; L2 site suspected; L3 site confirmed; OK works; ok works but must copy/paste address
			,	"link_realtor"           : function(){try{return  /*OK* /        r.avm.dataset.realtor.link                              }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_realEstate"        : function(){try{return  /*OK* /        r.avm.dataset.realEstate.link                           }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_homeGain"          : function(){try{return  /*L3* /        r.avm.dataset.homeGain.link                             }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_trulia"            : function(){try{return  /*OK* /        r.avm.dataset.trulia.link                               }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_propertyShark"     : function(){try{return  /*ok* /        r.link.propertyShark                                    }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_neighborhoodScout" : function(){try{return  /*ok* /        r.link.neighborhoodScout                                }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_zipSkinny"         : function(){try{return  /*ok* /        r.link.zipSkinny                                        }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_chase"             : function(){try{return  /*ok* /        r.link.chase                                            }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_boa"               : function(){try{return  /*ok* /        r.link.boa                                              }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_homesCom"          : function(){try{return  /*ok* /        r.link.homesCom                                         }catch(e){Logger.log(e.message);return "";}}() //
										   } */
	} // db_id MyBid // arv rep cof com city state zip sa useCode beds baths sf sf_round lot lot_round yearBuilt taxVal taxVal_round lastSoldPrice lastSoldPrice_round lastSoldYear taxAmt taxAmt_round ask ask_round autoEst autoEst_round sdPct popCount rent rent_round ratio grm ia ia_round psf avmStatSet // link_googleMap link_yahoo link_zillow link_zillowdetails link_eppraisal link_realtor link_realEstate link_homeGain link_trulia link_propertyShark link_neighborhoodScout link_zipSkinny link_chase link_boa link_homesCom
	var keys=Object.keys(ob[i].nolink),z=keys.length;while(z--){out.records[i][keys[z]]=              ob[i].nolink[keys[z]]                                   }
     // keys=Object.keys(ob[i].  link),z=keys.length;while(z--){out.records[i][keys[z]]='<a href="' + ob[i].  link[keys[z]] + '" target="_blank">&#10151;</a>'}Logger.log(JSON.stringify(out.records[i]));
	}return out;}
function serveCalendar(){var START_YR=2006,ARR=[,"January","February","March","April","May","June","July","August","September","October","November","December"],d=new Date(),yr=d.getFullYear(),mo=d.getMonth()+1,ob=[],i,q,r,id,record,user=Session.getUser().getEmail(),db=ScriptDb.getMyDb(),out={"totalResultsCount":0,"records":[]};
    while(yr>START_YR){if(!--mo){mo=12;yr--;}q={table:"report",source:user/*Replace with company_id*/,year:yr,monthNum:mo};
        if(db.query(q).getSize()){r=db.query(q).next();}else{q.monthStr=ARR[mo];q.sortBy=1000*yr+mo;q.roi=[{timestamp:d.getTime(),amt:""}];r=db.load(db.save(q).getId());}
        out.records.push({
                    "db_id"              : function(){try{return LibraryjsUtil.rc4Encrypt("DktaE",r.getId())                             }catch(e){Logger.log(e.message);return "";}}() //
                ,   "sortBy"             : function(){try{return                                  r.sortBy                               }catch(e){Logger.log(e.message);return "";}}() //
                ,   "year"               : function(){try{return                                  r.year                                 }catch(e){Logger.log(e.message);return "";}}() //
                ,   "monthNum"           : function(){try{return                                  r.monthNum                             }catch(e){Logger.log(e.message);return "";}}() //
                ,   "monthStr"           : function(){try{return                                  r.monthStr                             }catch(e){Logger.log(e.message);return "";}}() //
                ,   "roi"                : function(){try{return                                  r.roi[0].amt                           }catch(e){Logger.log(e.message);return "";}}() //
		        });}out.totalResultsCount=out.records.length;Logger.log(JSON.stringify(out));return out;}
function t_serveCalendar(){var START_YR=2006,ARR=[,"January","February","March","April","May","June","July","August","September","October","November","December"],d=new Date(),t=d.getTime(),yr=d.getFullYear(),mo=d.getMonth()+1,ob=[],i,q,qr,rq,r,id,out={"totalResultsCount":0,"records":[]},user=Session.getUser().getEmail(),db=ScriptDb.getMyDb(),q={table:"report",source:user/*Replace with company_id*/},results=db.query(q);while(results.hasNext()){rq=results.next();
    while(yr>START_YR){if(!--mo){mo=12;yr--;}
        /*try{*/if(rq.year==yr&rq.monthNum==mo){r=rq}/*}*catch(e)*/else{qr=q;qr.monthStr=ARR[mo];qr.sortBy=1000*yr+mo;qr.roi=[{timestamp:t,amt:""}];r=db.load(db.save(qr).getId());}
        out.records.push({
                    "db_id"              : function(){try{return LibraryjsUtil.rc4Encrypt("DktaE",r.getId())                             }catch(e){Logger.log(e.message);return "";}}() //
                ,   "sortBy"             : function(){try{return                                  r.sortBy                               }catch(e){Logger.log(e.message);return "";}}() //
                ,   "year"               : function(){try{return                                  r.year                                 }catch(e){Logger.log(e.message);return "";}}() //
                ,   "monthNum"           : function(){try{return                                  r.monthNum                             }catch(e){Logger.log(e.message);return "";}}() //
                ,   "monthStr"           : function(){try{return                                  r.monthStr                             }catch(e){Logger.log(e.message);return "";}}() //
                ,   "roi"                : function(){try{return                                  r.roi[0].amt                           }catch(e){Logger.log(e.message);return "";}}() //
		        });}}out.totalResultsCount=out.records.length;/*Logger.log(JSON.stringify(out));*/return out;}
-------------------------------------- Sell.html --------------------------------------
<div style="font-family:arial;font-size:75%;color:#777777;">
    <form id="form_reg"><!--Reference: https://developers.google.com/apps-script/guides/html-service-communication#forms--><!--Reference: https://developers.google.com/apps-script/guides/html-service-communication#user_objects-->
        <span style="font-weight:bold">
        Seller Info</span> | <!-- Load user data via google.script.run.withSuccessHandler(populateUser).sendUserToClient(); Reference: https://developers.google.com/apps-script/guides/html-service-communication#success_handlers -->
        Full name      <input type="text"   style="color:#777777" id="fullname"        name="fullname">
        Phone          <input type="text"   style="color:#777777" id="phone"           name="phone" pattern="^\d{10}$"  size="8" maxlength="10" title="Area code. No punctuation. Example: 2125551234">
        Email list     <input type="text"   style="color:#777777" id="emailListString" name="emailListString" size="50" title="List of email addresses to notify. Separate with comma. Separately process list as text file. Then copy and paste.">
        Ask            <select              style="color:#777777" id="ask"             name="ask" size="1" title="EARN — How many points do you ask others to pay you to broker note sales to your existing buyer pool?"><option></option><option>0.00</option><option>0.25</option><option>0.50</option><option>0.75</option><option>1.00</option><option>1.25</option><option>1.50</option><option>1.75</option><option>2.00</option><option>3.25</option><option>3.50</option><option>3.75</option><option>3.00</option><option>4.25</option><option>4.50</option><option>4.75</option><option>5.00</option><option>6.25</option><option>6.50</option><option>6.75</option><option>7.00</option><option>7.25</option><option>7.50</option><option>7.75</option><option>8.00</option><option>8.25</option><option>8.50</option><option>8.75</option><option>9.00</option><option>9.25</option><option>9.50</option><option>9.75</option><option>10.00</option></select>
        Bid            <select              style="color:#777777" id="bid"             name="bid" size="1" title="PAY — How many points do you offer to have others sell notes on your behalf to their buyer pool?"><option></option><option>0.00</option><option>0.25</option><option>0.50</option><option>0.75</option><option>1.00</option><option>1.25</option><option>1.50</option><option>1.75</option><option>2.00</option><option>3.25</option><option>3.50</option><option>3.75</option><option>3.00</option><option>4.25</option><option>4.50</option><option>4.75</option><option>5.00</option><option>6.25</option><option>6.50</option><option>6.75</option><option>7.00</option><option>7.25</option><option>7.50</option><option>7.75</option><option>8.00</option><option>8.25</option><option>8.50</option><option>8.75</option><option>9.00</option><option>9.25</option><option>9.50</option><option>9.75</option><option>10.00</option></select>
                       <input type="checkbox" name="agreed" id="agreed" xvalue="true">I agree to the <a target="_blank" href="https://docs.google.com/document/d/1X8E5xzWGtGyUOy1PmAkwJ51vU6qX12rxUF8JjhpWRUU/preview">Groundrules</a>.               
                       <input type="button" value="Submit" onclick="google.script.run.withSuccessHandler(updateButton).withUserObject(this).processForm_registerSeller(this.parentNode)">
    </form>
    <form id="form_note"><!--Reference: https://developers.google.com/apps-script/guides/html-service-communication#forms--><!--Reference: https://developers.google.com/apps-script/guides/html-service-communication#user_objects-->
        <span style="font-weight:bold">
        [+Add] List New Note </span> |
        <span style="font-style:italic">Loan</span> | 
        AskRate        <input type="text"   style="color:#777777" name="askRate"   size="1"                   title="Interest rate paid to note buyer. Example: 13">
        AskPts         <input type="text"   style="color:#777777" name="askPts"    size="1"                   title="Points paid to note buyer. Example: 1.5">
        BorRate        <input type="text"   style="color:#777777" name="borRate"   size="1"                   title="Interest rate paid by borrower. Example: 15">
        BorPts         <input type="text"   style="color:#777777" name="borPts"    size="1"                   title="Points paid by borrower. Example: 3">
        Amount         <input type="text"   style="color:#777777" name="amount"    size="3"                   title="Example: 94250">
        LTV%           <input type="text"   style="color:#777777" name="ltv"       size="1"                   title="Example: 65">
        Term           <input type="text"   style="color:#777777" name="term"      size="1"                   title="In months. Example: 18">
        Purpose    <!--<input type="text"   style="color:#777777" name="purpose"                              title="Example: Refinance">-->
                       <select  id="type"   style="color:#777777" name="purpose"   size="1"                   title="" onchange="">
                           <option></option>
                           <option>Purchase</option>
                           <option>Refinance</option>
                       </select>
         <!-- Purchase <input type="radio"  style="color:#777777" name="purpose"            value="purchase"  title="Purchase money"        >
              Refi     <input type="radio"  style="color:#777777" name="purpose"            value="refinance" title="Refinance or cash out"  > | -->
        Exit       <!--<input type="text"   style="color:#777777" name="exit"                                 title="Exit strategy. Examples: Refi, Sell, Flip, etc." >   -->
                       <select  id="exit"   style="color:#777777" name="exit"      size="1"                   title="" onchange="">
                           <option></option>
                           <option>Sell</option>
                           <option>Refi</option>
                       </select>
         <!-- Sell     <input type="radio"  style="color:#777777" name="exit"               value="sell"      title="Sell"                   >
              Refi     <input type="radio"  style="color:#777777" name="exit"               value="refinance" title="Refinance"> | -->
        Notes          <input type="text"   style="color:#777777" name="notes"     size="1"                   title="Deal highlights. Example: 1. Borrower purchased through short sale in August. 2. Borrower has updated property. 3. Borrower has tenant with good cash flow of $1,500/month. 4. Repeat Borrower in good standing with company with one loan paid off.">
        SellCarry      <input type="text"   style="color:#777777" name="sellCarry" size="3"                   title="Seller carryback financing. If any. Example: 125000">
   <br> <span style="font-style:italic">Collateral</span> |
        Street         <input type="text"   style="color:#777777" name="sa"                                   title="Example: 123 Main St">
        City           <input type="text"   style="color:#777777" name="city"                                 title="Example: Cambridge">
        State          <input type="text"   style="color:#777777" name="state"     size="1"                   title="Example: MA">
        Zip            <input type="text"   style="color:#777777" name="zip"       size="2"                   title="Example: 02139">
        Use        <!--<input type="text"   style="color:#777777" name="use"                                  title="Example: Single Family Residence">-->
                       <select id="use"     style="color:#777777" name="use"       size="1"                   title="SFR: Single Family Residential" onchange="">
                           <option></option>
                           <option>SFR</option>
                           <option>Condo</option>  
                           <option>2-4</option>
                           <option>Apt</option>
                       </select>
        Beds           <input type="text"   style="color:#777777" name="beds"      size="1"                   title="Example: 2">
        Baths          <input type="text"   style="color:#777777" name="baths"     size="1"                   title="Use decimals when necessary. Example: 2.25">
        Sqft           <input type="text"   style="color:#777777" name="sqft"      size="1"                   title="No commas. Example: 1175">
        ARV            <input type="text"   style="color:#777777" name="arv"       size="3"                   title="No commas. Example: 210000">
        Appraisal      <input type="text"   style="color:#777777" name="appraisal" size="3"                   title="As is. Example: 145000">
        PurPrice       <input type="text"   style="color:#777777" name="purPrice"  size="3"                   title="Purchase price. If purchase money loan. Example: 145000">
   <br> <span style="font-style:italic">Borrower</span> |
        GoodPay        <input type="text"   style="color:#777777" name="payGood"   size="1"                   title='Borrower “Good Pay” track record history with your company. Enter how many loans the borrower has successfully repaid to your company. Example: 10'>
        BadPay         <input type="text"   style="color:#777777" name="payBad"    size="1"                   title='Borrower “Bad Pay” history. Enter number of prior loan defaults with your company. Example: 0'>
        SchedRE        <input type="text"   style="color:#777777" name="schedRE"   size="1"                   title='Enter number of properties the borrower currently has in inventory i.e., “Schedule of Real Estate.” Example: 10'>
        Image          <input type="file"                         name="filePic"                              title="Upload picture of subject">
        Documents      <input type="file"                         name="fileDoc"                              title='Upload “deal stack” (as PDF file)'>    
                       <input type="button" value="Submit New Note" onclick="google.script.run.withSuccessHandler(updateButton).withUserObject(this).processForm_addNote(this.parentNode)">
                       <input type="button" value="Reset Form"      onclick="google.script.run.withSuccessHandler(resetForm)   .withUserObject(this).auth               (this.parentNode)">
    </form>
</div>
<!-- --------------------- Put script tags below this line. --------------------- -->
<!-- Reference: https://developers.google.com/apps-script/guides/html-service-best-practices?hl=en#load_javascript_last -->
<!-- Reference: https://developers.google.com/apps-script/guides/html-service-best-practices?hl=en#dont_use_html_head_or_body_tags --><!-- Dont use <html>, <head> or <body> tags; -->
<script>function updateButton(userObject,button){document.getElementById("form_note").reset();button.value="Success!";}</script>
<script>function resetForm   (userObject,button){document.getElementById("form_note").reset();                        }</script>
<script>function populateUser(r){try{if(r.record[0]&&r.record[0].fullname       ){document.getElementById("fullname"       ).value=r.record[0].fullname       }}catch(e){Logger.log(e.message)}
                                 try{if(r.record[0]&&r.record[0].phone          ){document.getElementById("phone"          ).value=r.record[0].phone          }}catch(e){Logger.log(e.message)}
                                 try{if(r.record[0]&&r.record[0].emailListString){document.getElementById("emailListString").value=r.record[0].emailListString}}catch(e){Logger.log(e.message)}
                                 try{if(r.record[0]&&r.record[0].ask            ){document.getElementById("ask"            ).value=r.record[0].ask            }}catch(e){Logger.log(e.message)}
                                 try{if(r.record[0]&&r.record[0].bid            ){document.getElementById("bid"            ).value=r.record[0].bid            }}catch(e){Logger.log(e.message)}}
        google.script.run.withSuccessHandler(populateUser).sendUserToClient();
</script>
<!--
Loan Scenarios to add:
1. Money held in trust for rehab.
2. Multiple properties / cross-collateralization
-->
-------------------------------------- Buy.html --------------------------------------
Blank
-------------------------------------- Sell01.html --------------------------------------
<div style="font-family:arial;font-size:75%;color:#777777;">
    <form id="form_reg"><!--Reference: https://developers.google.com/apps-script/guides/html-service-communication#forms--><!--Reference: https://developers.google.com/apps-script/guides/html-service-communication#user_objects-->
        <span style="font-weight:bold">
        Seller Info</span> | <!-- Load user data via google.script.run.withSuccessHandler(populateUser).sendUserToClient(); Reference: https://developers.google.com/apps-script/guides/html-service-communication#success_handlers -->
        Full name      <input type="text"   style="color:#777777" name="fullname" id="fullname">
        Phone          <input type="text"   style="color:#777777" name="phone" id="phone" pattern="^\d{10}$" size="8" maxlength="10" title="Area code. No punctuation. Example: 2125551234">
        Email list     <input type="text"   style="color:#777777" name="emailListString" id="emailListString" size="50" title="List of email addresses to notify. Separate with comma. Separately process list as text file. Then copy and paste.">
                       <input type="button" value="Update Contact Info" onclick="google.script.run.withSuccessHandler(updateButton).withUserObject(this).processForm_registerSeller(this.parentNode)">
    </form>
    <form id="form_note"><!--Reference: https://developers.google.com/apps-script/guides/html-service-communication#forms--><!--Reference: https://developers.google.com/apps-script/guides/html-service-communication#user_objects-->
        <span style="font-weight:bold">
        [+] Add New Note </span> |
        <span style="font-style:italic">Loan</span> | 
        BuyRate        <input type="text"   style="color:#777777" name="buyRate"   size="1"                   title="Interest rate paid to note buyer. Example: 13">
        BuyPts         <input type="text"   style="color:#777777" name="buyPts"    size="1"                   title="Points paid to note buyer. Example: 1.5">
        BorRate        <input type="text"   style="color:#777777" name="borRate"   size="1"                   title="Interest rate paid by borrower. Example: 15">
        BorPts         <input type="text"   style="color:#777777" name="borPts"    size="1"                   title="Points paid by borrower. Example: 3">
        Amount         <input type="text"   style="color:#777777" name="amount"    size="3"                   title="Example: 94250">
        LTV%           <input type="text"   style="color:#777777" name="ltv"       size="1"                   title="Example: 65">
        Term           <input type="text"   style="color:#777777" name="term"      size="1"                   title="In months. Example: 18">
        Purpose    <!--<input type="text"   style="color:#777777" name="purpose"                              title="Example: Refinance">-->
                       <select  id="type"   style="color:#777777" name="purpose"   size="1"                   title="" onchange="">
                           <option></option>
                           <option>Purchase</option>
                           <option>Refinance</option>
                       </select>
         <!-- Purchase <input type="radio"  style="color:#777777" name="purpose"            value="purchase"  title="Purchase money"        >
              Refi     <input type="radio"  style="color:#777777" name="purpose"            value="refinance" title="Refinance or cash out"  > | -->
        Exit       <!--<input type="text"   style="color:#777777" name="exit"                                 title="Exit strategy. Examples: Refi, Sell, Flip, etc." >   -->
                       <select  id="exit"   style="color:#777777" name="exit"      size="1"                   title="" onchange="">
                           <option></option>
                           <option>Sell</option>
                           <option>Refi</option>
                       </select>
         <!-- Sell     <input type="radio"  style="color:#777777" name="exit"               value="sell"      title="Sell"                   >
              Refi     <input type="radio"  style="color:#777777" name="exit"               value="refinance" title="Refinance"> | -->
        Notes          <input type="text"   style="color:#777777" name="notes"     size="1"                   title="Deal highlights. Example: 1. Borrower purchased through short sale in August. 2. Borrower has updated property. 3. Borrower has tenant with good cash flow of $1,500/month. 4. Repeat Borrower in good standing with company with one loan paid off.">
        SellCarry      <input type="text"   style="color:#777777" name="sellCarry" size="3"                   title="Seller carryback financing. If any. Example: 125000">
   <br> <span style="font-style:italic">Collateral</span> |
        Street         <input type="text"   style="color:#777777" name="sa"                                   title="Example: 123 Main St">
        City           <input type="text"   style="color:#777777" name="city"                                 title="Example: Cambridge">
        State          <input type="text"   style="color:#777777" name="state"     size="1"                   title="Example: MA">
        Zip            <input type="text"   style="color:#777777" name="zip"       size="2"                   title="Example: 02139">
        Use        <!--<input type="text"   style="color:#777777" name="use"                                  title="Example: Single Family Residence">-->
                       <select id="use"     style="color:#777777" name="use"       size="1"                   title="SFR: Single Family Residential" onchange="">
                           <option></option>
                           <option>SFR</option>
                           <option>Condo</option>  
                           <option>2-4</option>
                           <option>Apt</option>
                       </select>
        Beds           <input type="text"   style="color:#777777" name="beds"      size="1"                   title="Example: 2">
        Baths          <input type="text"   style="color:#777777" name="baths"     size="1"                   title="Use decimals when necessary. Example: 2.25">
        Sqft           <input type="text"   style="color:#777777" name="sqft"      size="1"                   title="No commas. Example: 1175">
        ARV            <input type="text"   style="color:#777777" name="arv"       size="3"                   title="No commas. Example: 210000">
        Appraisal      <input type="text"   style="color:#777777" name="appraisal" size="3"                   title="As is. Example: 145000">
        PurPrice       <input type="text"   style="color:#777777" name="purPrice"  size="3"                   title="Purchase price. If purchase money loan. Example: 145000">
   <br> Image          <input type="file"                         name="filePic"                              title="Picture of subject">
        Documents      <input type="file"                         name="fileDoc"                              title='Deal “stack” as PDF file'>    
                       <input type="button" value="Submit New Note" onclick="google.script.run.withSuccessHandler(updateButton).withUserObject(this).processForm_addNote(this.parentNode)">
                       <input type="button" value="Reset Form"      onclick="google.script.run.withSuccessHandler(resetForm)   .withUserObject(this).auth               (this.parentNode)">
    </form>
</div>
<!-- --------------------- Put script tags below this line. --------------------- -->
<!-- Reference: https://developers.google.com/apps-script/guides/html-service-best-practices?hl=en#load_javascript_last -->
<!-- Reference: https://developers.google.com/apps-script/guides/html-service-best-practices?hl=en#dont_use_html_head_or_body_tags --><!-- Dont use <html>, <head> or <body> tags; -->
<script>function updateButton(userObject,button){document.getElementById("form_note").reset();button.value="Success!";}</script>
<script>function resetForm   (userObject,button){document.getElementById("form_note").reset();                        }</script>
<script>function populateUser(r){try{if(r.record[0]&&r.record[0].fullname       ){document.getElementById("fullname"       ).value=r.record[0].fullname       }}catch(e){Logger.log(e.message)}
                                 try{if(r.record[0]&&r.record[0].phone          ){document.getElementById("phone"          ).value=r.record[0].phone          }}catch(e){Logger.log(e.message)}
                                 try{if(r.record[0]&&r.record[0].emailListString){document.getElementById("emailListString").value=r.record[0].emailListString}}catch(e){Logger.log(e.message)}}
        google.script.run.withSuccessHandler(populateUser).sendUserToClient();
</script>
<!--
Loan Scenarios to add:
1. Money held in trust for rehab.
2. Multiple properties / cross-collateralization
-->
-------------------------------------- Sandbox.html --------------------------------------
<div style="font-family:arial;font-size:75%;color:#777777;">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"></script>
    <div>Choose date<input type="text" name="date" id="datepicker" style="color:#777777"/></div>
    <script>$("#datepicker").datepicker();</script> <!-- // Reference: http://stackoverflow.com/questions/9336163/jquery-ui-with-google-apps-script // Search: use jquery with google apps script html service -- >
</div>