// JSON visualization | viewer: http://chris.photobooks.com/json/default.htm
// function getEmailQuota(){Logger.log("Remaining email quota: " + MailApp.getRemainingDailyQuota());}
// Note: to accept doPost() from affiliate, (design decision:) must set: Publish > Deploy as web app > Execute the app as: me, Who has access to the app: Anyone, even anonymous // Otherwise, script will not run at server (though, client will receive responseCode=200); client response (200) is Google accounts sign-in page/form  // Decision Benefits: 1. script runs 2. script authorization bypass (i.e., not needed at UI) // Decision Costs: 1. Looser script security; mitigated by a. Site level access restrictions/permissions b. key method (e.g., switch/case k:foo)
function auth   (){}
function timer  (){Logger.log(new Date().getTime())}//1388228703613
function backup (){var desc="Scrape Realtor Backup — timestamp:"+new Date().getTime(),id,out=[],db=ScriptDb.getMyDb(),results=db.query({});while(results.hasNext()){out.unshift(results.next())}id=DriveApp.createFile(desc,JSON.stringify(out),MimeType.HTML).setDescription(desc);Logger.log(id);}
function print  (){var desc="Scrape Realtor Print — timestamp:"+new Date().getTime(),id,out=[],db=ScriptDb.getMyDb(),results=db.query({isRaw:false});while(results.hasNext()){out.unshift(results.next())}id=DriveApp.createFile(desc,JSON.stringify(out),MimeType.HTML).setDescription(desc);Logger.log(id);}
function print_test(str){var desc="Scrape Realtor Print — timestamp:"+new Date().getTime();DriveApp.createFile(desc,str,MimeType.HTML);}
function size   (){var db=ScriptDb.getMyDb();Logger.log(db.query({table:db.anyValue()/*isRaw:false*/}).getSize())}
function showOne(){var db=ScriptDb.getMyDb();Logger.log(JSON.stringify(db.query({table:db.anyValue()/*isRaw:false*/}).next()));} // Show all records in database // Reference: https://developers.google.com/apps-script/scriptdb#saving_data
function showAll(){var db=ScriptDb.getMyDb(),arr=[],r,results=db.query({});while(results.hasNext()){r=results.next();arr.push(r)}Logger.log(JSON.stringify(arr))} // Show all records in database // Reference: https://developers.google.com/apps-script/scriptdb#saving_data
//function del    (){var db=ScriptDb.getMyDb(),arr=[],r,results=db.query({xisRaw:false});while(results.hasNext()){arr.push(results.next().getId());}db.removeByIdBatch(arr,false);} // Replaced: while(results.hasNext()){r=results.next();db.remove(r);}}
//function mod    (){var db=ScriptDb.getMyDb(),arr=[],r,results=db.query({xtable:"note"/*lienPos:db.anyOf(["1st",false,db.not(db.anyValue())])*/});while(results.hasNext()){r=results.next();try{r.pctLtv=Math.round(100*r.balCur/r.estValue)}catch(e){r.pctLtv="";Logger.log(e.message)}/*r.lienPos=1;*/arr.push(r);}db.saveBatch(arr,false)}
//function getEmailQuota(){Logger.log("Remaining email quota: " + MailApp.getRemainingDailyQuota());}
function realtorScrape(inState,inCity){//var inState=inState||"CA",inCity=inCity||"San-Diego";//Not case-sensitive//Returns array of situs objects from Realtor.com foreclosure MLS listings//URL:http://www.realtor.com/foreclosures/San-Diego_CA/sby-1/pg-2?pgsz=200//Alt URL:act="http://www.realtor.com/search/searchresults.aspx?sby=1&pgsz=10&loc=phoenix%2c+az&pr=false&status=foreclosures&pg=1"; // var LOAD=["https://sites.google.com/site/itr5k9zw23yzmxuaf5nb399c0ywb98/home/jsLoad.js","googleScripts"];eval(UrlFetchApp.fetch(LOAD[0]).getContentText());var files=load(LOAD[1]);var i=files.length;while(i---1){eval(UrlFetchApp.fetch(files[i]).getContentText())} // Notes: For scraping page-by-page, need to determine 3rd argument (token) in scrape function. Hopefully, this will work at least until scrape volume reaches 200 and we need to paginate.
    var i,str,data=[],out=[],act="http://www.realtor.com/foreclosures/"+inCity+"_"+inState+"/type-single-family-home"+"/sby-1"/*+"/pg-"+(++pg)*/+"?ml=4&pgsz=200" // "http://www.realtor.com/foreclosures/San-Diego_CA/type-single-family-home/sby-1?ml=4&pgsz=200"
    ,   KEY = [ , "link" , "address_long_1" , "link_photo" , "address_long_2" , "sa"                     , "city"         , "state"          , "zip"            , "latitude"   , "longitude"  , "listingPrice"  , "beds"         , "baths"         , "sqft"         , "lot"          , "propertyType"          , "brokeredBy"          ]
    ,   QUE = [ , "href" , "title"          , "src"        , "alt"            , "listing-street-address" , "listing-city" , "listing-region" , "listing-postal" , "latitude"   , "longitude"  , "listing-price" , "listing-beds" , "listing-baths" , "listing-sqft" , "listing-sqft" , "listing-property-type" , "listing-brokered-by" ]
    ,   BEG = [ , "\""   , "\""             , "\""         , "\""             , ">"                      , ">"            , ">"              , ">"              , "content=\"" , "content=\"" , "$"             , "<em>"         , "<em>"          , "<em>"         , "<em>"         , ">"                     , ":"                   ]
    ,   END = [ , "\""   , "\""             , "\""         , "\""             , "<"                      , "<"            , "<"              , "<"              , "\""         , "\""         , "<"             , "<"            , "<"             , "<"            , "<"            , "<"                     , "\""                  ]
    ;   try{if(UrlFetchApp.fetch(act).getResponseCode()==200){str=UrlFetchApp.fetch(act).getContentText()}else{return}}catch(e){Logger.log(e.message);return} //Logger.log(act);}
	var arr=str.split("listing-wrap").slice(5);i=arr.length;while(i--){data[i]                = LibraryjsUtil._scrapeDataset(arr[i],KEY,QUE,BEG,END,["$",",","%"],["","",""],true);
                                                                       data[i].isPriceReduced = (arr[i].indexOf("i-price-reduced"  )>-1);
                                                                       data[i].isForeclosure  = (arr[i].indexOf("badge-foreclosure")>-1);
                                                                       data[i].isBankOwned    = (arr[i].indexOf("badge-bank-owned" )>-1);//Logger.log(isForeclosure);Logger.log(isPriceReduced);Logger.log(isBankOwned);}
							              /* Special Processing */ try{data[i].propertyType   = LibraryjsUtil.convrepl   (data[i].propertyType,{"Single Family Home":"SFR"/*,"Commercial":"CRE","Multifamily":"MUL","Hospitality":"CRE"*/},arr[i].propertyType);}catch(e){Logger.log(e.message)}
                                                                   try{data[i].sa             = LibraryjsUtil.toCaseTitle(data[i].sa                                                                                                                          );}catch(e){Logger.log(e.message)}
                                                                   try{data[i].city           = LibraryjsUtil.toCaseTitle(data[i].city                                                                                                                        );}catch(e){Logger.log(e.message)}
                                                                        out[i]                = {isRaw:true,source:{name:"Realtor",data:data[i]},market:{city:inCity,state:inState}};
                                                                      }/*Logger.log(JSON.stringify(out));*/return out}
function realtorScrape_call(city,state){db=ScriptDb.getMyDb(),arr=realtorScrape("San-Diego","CA");/*Logger.log(arr)*/db.saveBatch(arr,false);return}
function realtorAddAvm(){var db=ScriptDb.getMyDb(),r,q,results=db.query({isRaw:true});while(results.hasNext()){r=results.next();q=LibraryjsAvm.avmJson(r);q.item=LibraryjsUtil.toBase62(Number(r.getId().slice(1)));db.save(q);db.remove(r);}}
// Instructions: To load db with data, 1. Run realtorScrape_call(city,state); 2. Run realtorAddAvm();
// ============================== IMPORTED FROM DEALDIGGER™ =============================
// ----------------------- Code.gs -----------------------
function doPost(e){return x.y();}
function doGet(e){ // References: https://developers.google.com/apps-script/guides/html-service-communication#private_functions // https://sites.google.com/site/appsscripttutorial/miscellaneous/creating-form-elements-dynamically-using-google-apps-script-gas
 // if(e && e.parameter && e.parameter.jsoncallback){return ContentService.createTextOutput("foo({result:'<strong>Hello</strong> World'});").setMimeType(ContentService.MimeType.TEXT);}
    if(e && e.parameter && e.parameter.k){var k=e.parameter.k,m=e.parameter.m,p=e.parameter;switch(k){
            case   /* register-buyer   */ "fruif01iaqqdgmqq1glu" : return ContentService.createTextOutput(e.parameter.jsoncallback+"({'result':'<div style=\"overflow:hidden\"><iframe scrolling=\"no\"   style=\"xmargin-top:-200px;width:100%;height:1200px;\" src=\"https://sites.google.com/site/dealdiggeronline/parties/buyer/register-buyer#sites-canvas-main-content\"      ></iframe></div>'})").setMimeType(ContentService.MimeType.JSON      );break; // References // http://www.dimpost.com/2012/12/iframe-how-to-display-specific-part-of.html // http://stackoverflow.com/questions/5676672/how-do-i-crop-the-contents-of-an-iframe-to-show-a-part-of-a-page/14004622#14004622
            case   /* pub-auc-data     */ "9l4y95xhwwi8q2hbkslp" : return ContentService.createTextOutput(e.parameter.    callback+"(" + JSON.stringify(serveBuyers  ( )) + ")"                                                                                                                                                                                                                       ).setMimeType(ContentService.MimeType.JSON      );break; // References // http://www.dimpost.com/2012/12/iframe-how-to-display-specific-part-of.html // http://stackoverflow.com/questions/5676672/how-do-i-crop-the-contents-of-an-iframe-to-show-a-part-of-a-page/14004622#14004622
            case   /* receive input    */ "2kpco3hg68eo6alklck6" : return                                                                   /* x.y() */ receiveBuyer (p)                                                                                                                                                                                                                                                                               ;break; // References // http://www.dimpost.com/2012/12/iframe-how-to-display-specific-part-of.html // http://stackoverflow.com/questions/5676672/how-do-i-crop-the-contents-of-an-iframe-to-show-a-part-of-a-page/14004622#14004622
         default                                                 :                                                                                                         ;break;}} 
    if(SitesApp.getActivePage()){var pageName = SitesApp.getActivePage().getName();switch(pageName){
            case   "authorize"             : return authorize                           (                       )                                                          ;break;
			case   "sandbox2"              : return HtmlService.createHtmlOutputFromFile("sandbox2"             ).setSandboxMode(HtmlService.SandboxMode.NATIVE           );break; // Reference: https://developers.google.com/apps-script/guides/html-service-caja#setsandboxmode
         default                           :                                                                                                                                break;}}}
// ---------------------------------------------------------------- AUTHPAGE ----------------------------------------------------------------
function authorize(){return HtmlService.createHtmlOutput("<div align='center' style='color:#808080;font-family:verdana;color:#1925AF;font-weight:bold;margin-top:15px;'>Authorization successful!<div style='color:#808080;font-size:smaller;font-weight:normal;'>You may now access all features</div><img src='https://lh5.googleusercontent.com/-BIZ7mfp5ckk/TVZR8NYKMKI/AAAAAAAABS0/SR1Pg44rAGs/s1600/checkmark1.jpg'></div>")}
// ------------------------------------------------------------------ DEALS -------------------------------------------------------------------
function serveBuyers(){var ob=[],arr=[],i,j,k,r,t=[],zil=[],user=Session.getUser().getEmail(),out={"totalResultsCount":0,"records":[]},db=ScriptDb.getMyDb(),results=db.query({table:"situs",isRaw:false,source:{name:"Realtor"/*"ZipRealty"/*"ChuckWillman"/*"KennethGreen"*/}}).sortBy("avm.stat.ratio",db.ASCENDING/*DESCENDING*/,db.NUMERIC/*LEXICAL*/);while(results.hasNext()){r=results.next();i=out.totalResultsCount++;
	out.records[i]={};try{if(r.avm.dataset.zillow.searchresults.response.results.result){zil[i]=r.avm.dataset.zillow.searchresults.response.results.result}}catch(e){Logger.log(e.message);zil[i]={};} // Shortcut to Zillow results
	try{if(r.bids){arr[i]=r.bids;j=arr[i].length;while(j--){t[j]=0;if(arr[i][j].bidder==user&&(arr[i][j].time>t[j])/*&&(!arr[i][j].confirmed)*/){t[j]=arr[i][j].time;out.records[i].MyBid=arr[i][j].amount}}             }}catch(e){Logger.log(e.message)}; // "MyBid"
	ob[i] = {
		"nolink"                         : {
				"arv"                    : function(){try{return            r.arv                         .value                    }catch(e){Logger.log(e.message);return "";}}() // "arv" Strict input // ARV
			,	"ask"                    : function(){try{return            r.ask                                                   }catch(e){Logger.log(e.message);return "";}}() //
			,	"ask_round"              : function(){try{return Math.round(r.ask                                 / 1000 )          }catch(e){Logger.log(e.message);return "";}}() //
			,	"autoEst"                : function(){try{return            r.avm.stat.autoEst                                      }catch(e){Logger.log(e.message);return "";}}() //
			,	"autoEst_round"          : function(){try{return Math.round(r.avm.stat.autoEst                    / 1000 )          }catch(e){Logger.log(e.message);return "";}}() //
			,	"avmStatSet"             : function(){try{return            r.avm.stat.set                                          }catch(e){Logger.log(e.message);return "";}}() // "avmStatSet" Array of AVM statistics
			,	"baths"                  : function(){try{return            r.avm.combi.baths                                       }catch(e){Logger.log(e.message);return "";}}() //
			,	"beds"                   : function(){try{return            r.avm.combi.beds                                        }catch(e){Logger.log(e.message);return "";}}() //
			,	"city"                   : function(){try{return            r.address.city                                          }catch(e){Logger.log(e.message);return "";}}() //
			,	"cof"                    : function(){try{return            r.counter                     .value                    }catch(e){Logger.log(e.message);return "";}}() // "cof" Strict input // Counter
			,	"com"                    : function(){try{return            r.LST_Attributes[21].attribute_value                    }catch(e){Logger.log(e.message);return "";}}() // "com" Strict input // Comments 
			,	"full"                   : function(){try{return            r.address.full                                          }catch(e){Logger.log(e.message);return "";}}() //
			,	"grm"                    : function(){try{return Math.round(r.ask/(12*Number(zil[i].rentzestimate.amount.Text)))    }catch(e){Logger.log(e.message);return "";}}() // "grm" Compute gross rent margin
			,	"ia"                     : function(){try{return            r.incomeApproach                                        }catch(e){Logger.log(e.message);return "";}}() // "ia"  Compute price per income approach
			,	"ia_round"               : function(){try{return Math.round(r.incomeApproach                      / 1000 )          }catch(e){Logger.log(e.message);return "";}}() //
            ,   "item"                   : function(){try{return            r.item                                                  }catch(e){Logger.log(e.message);return "";}}() //
			,	"lastSoldPrice"          : function(){try{return            r.avm.combi.lastSoldPrice                               }catch(e){Logger.log(e.message);return "";}}() //
			,	"lastSoldPrice_round"    : function(){try{return Math.round(r.avm.combi.lastSoldPrice             / 1000 )          }catch(e){Logger.log(e.message);return "";}}() //
			,	"lastSoldYear"           : function(){try{return            r.avm.combi.lastSoldYear                                }catch(e){Logger.log(e.message);return "";}}() //
			,	"lot"                    : function(){try{return            r.avm.combi.lot.Text                                    }catch(e){Logger.log(e.message);return "";}}() //
			,	"lot_round"              : function(){try{return Math.round(r.avm.combi.lot.Text                  /  100 )          }catch(e){Logger.log(e.message);return "";}}() //
			,	"popCount"               : function(){try{return            r.avm.stat.popCount                                     }catch(e){Logger.log(e.message);return "";}}() //
			,	"psf"                    : function(){try{return Math.round(r.ask/*avm.stat.autoEst*//r.avm.combi.sqft)             }catch(e){Logger.log(e.message);return "";}}() // "psf" Compute price per square foot
			,	"ratio"                  : function(){try{return            r.avm.stat.ratio                                        }catch(e){Logger.log(e.message);return "";}}() // "rent"
			,	"rent"                   : function(){try{return Math.round(zil[i].rentzestimate.amount.Text             )          }catch(e){Logger.log(e.message);return "";}}() //
			,	"rent_round"             : function(){try{return Math.round(zil[i].rentzestimate.amount.Text      /  100 )          }catch(e){Logger.log(e.message);return "";}}() //
			,	"rep"                    : function(){try{return            r.repairs                     .value                    }catch(e){Logger.log(e.message);return "";}}() // "rep" Strict input // Repairs
			,	"sa"                     : function(){try{return            r.address.sa                                            }catch(e){Logger.log(e.message);return "";}}() //
			,	"sdPct"                  : function(){try{return            r.avm.stat.sdPct                                        }catch(e){Logger.log(e.message);return "";}}() //
			,	"sf"                     : function(){try{return            r.avm.combi.sqft                                        }catch(e){Logger.log(e.message);return "";}}() //
			,	"sf_round"               : function(){try{return Math.round(r.avm.combi.sqft                      /  100 )          }catch(e){Logger.log(e.message);return "";}}() //
			,	"state"                  : function(){try{return            r.address.state                                         }catch(e){Logger.log(e.message);return "";}}() //
            ,	"useCode"                : function(){try{return            r.avm.combi.useCode                                     }catch(e){Logger.log(e.message);return "";}}() //
			,	"taxAmt"                 : function(){try{return            r.avm.combi.taxAmt                                      }catch(e){Logger.log(e.message);return "";}}() //
			,	"taxAmt_round"           : function(){try{return Math.round(r.avm.combi.taxAmt                    /  100 )          }catch(e){Logger.log(e.message);return "";}}() //
			,	"taxVal"                 : function(){try{return            r.avm.combi.taxVal                                      }catch(e){Logger.log(e.message);return "";}}() //
			,	"taxVal_round"           : function(){try{return Math.round(r.avm.combi.taxVal                    / 1000 )          }catch(e){Logger.log(e.message);return "";}}() //
            ,	"yearBuilt"              : function(){try{return            r.avm.combi.built                                       }catch(e){Logger.log(e.message);return "";}}() //
			,	"zip"                    : function(){try{return            r.address.zip                                           }catch(e){Logger.log(e.message);return "";}}() //
										   }
	,	"link"		                     : {
				"link_boa"               : function(){try{return  /*ok*/    r.link.boa                                              }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_chase"             : function(){try{return  /*ok*/    r.link.chase                                            }catch(e){Logger.log(e.message);return "";}}() //
            ,	"link_eppraisal"         : function(){try{return  /*L1*/    r.avm.dataset.eppraisal.link                            }catch(e){Logger.log(e.message);return "";}}() // Errors: L1 local; L2 site suspected; L3 site confirmed; OK works; ok works but must copy/paste address
			,	"link_googleMap"         : function(){try{return  /*OK*/    r.link.gmap                                             }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_homeGain"          : function(){try{return  /*L3*/    r.avm.dataset.homeGain.link                             }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_homesCom"          : function(){try{return  /*ok*/    r.link.homesCom                                         }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_neighborhoodScout" : function(){try{return  /*ok*/    r.link.neighborhoodScout                                }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_propertyShark"     : function(){try{return  /*ok*/    r.link.propertyShark                                    }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_realEstate"        : function(){try{return  /*OK*/    r.avm.dataset.realEstate.link                           }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_realtor"           : function(){try{return  /*OK*/    r.avm.dataset.realtor.link                              }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_trulia"            : function(){try{return  /*OK*/    r.avm.dataset.trulia.link                               }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_yahoo"             : function(){try{return  /*OK*/    r.link.yahoo	   					                    }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_zillow"            : function(){try{return  /*OK*/    r.link.zillow                                           }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_zillowdetails"     : function(){try{return  /*OK*/    zil[i].links.homedetails.Text                           }catch(e){Logger.log(e.message);return "";}}() //
			,	"link_zipRealty"         : function(){try{return            ""                                                      }catch(e){Logger.log(e.message);return "";}}() //            
			,	"link_zipSkinny"         : function(){try{return  /*ok*/    r.link.zipSkinny                                        }catch(e){Logger.log(e.message);return "";}}() //
										   }
	} // db_id MyBid // arv rep cof com city state zip sa useCode beds baths sf sf_round lot lot_round yearBuilt taxVal taxVal_round lastSoldPrice lastSoldPrice_round lastSoldYear taxAmt taxAmt_round ask ask_round autoEst autoEst_round sdPct popCount rent rent_round ratio grm ia ia_round psf avmStatSet // link_googleMap link_yahoo link_zillow link_zillowdetails link_eppraisal link_realtor link_realEstate link_homeGain link_trulia link_propertyShark link_neighborhoodScout link_zipSkinny link_chase link_boa link_homesCom
	var keys=Object.keys(ob[i].nolink),z=keys.length;while(z--){out.records[i][keys[z]]=              ob[i].nolink[keys[z]]                                   }
		keys=Object.keys(ob[i].  link),z=keys.length;while(z--){out.records[i][keys[z]]='<a href="' + ob[i].  link[keys[z]] + '" target="_blank">&#10151;</a>'}Logger.log(JSON.stringify(out.records[i]));
	}return out;}
function receiveBuyer(p){Logger.log(JSON.stringify(p));var db=ScriptDb.getMyDb(),user=Session.getUser().getEmail(),d=new Date().getTime(),r=db.load(/*p.db_id*/db.query({item:p.item}).next().getId());//var ob={};ob[d]=p.MyBid;if(r.bids==null){r.bids={};r.bids[user]=[];r.bids[user].unshift(ob);}else{r.bids[user].unshift(ob);} // Gets latest bid
    if(r.bids==null){r.bids=[]}r.bids.unshift({bidder:user,amount:p.MyBid,time:d,confirmed:false});db.saveBatch([r,{table:"bid",id:r.getId(),amount:p.MyBid,bidder:user,time:d,confirmed:false}],false);return;}
